# Generated by Django 5.1.1 on 2024-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
